# Write a NumPy program to test whether none of the elements of a given array is zero.

In [2]:
import numpy as np
arr = np.array([0,10,20,30,40,50,60])
arr[arr == 0] = True
arr

array([ 1, 10, 20, 30, 40, 50, 60])

# Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [4]:
arr = np.array([0,5,0,9,0,0,0,20])
arr[arr != 0] = True
arr

array([0, 1, 0, 1, 0, 0, 0, 1])

# Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given

In [5]:
x = np.array([1,2,3])
y = np.array([1,5,3])
x == y

array([ True, False,  True])

# Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [9]:
A = np.zeros((1,10))
B = np.ones((1,10))
C = np.ones((1,10)) * 5
np.block([[A],[B],[C]])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

# Write a NumPy program to create an array of the integers from 30 to70.

In [22]:
np.linspace(30,70,9)

array([30., 35., 40., 45., 50., 55., 60., 65., 70.])

# Write a NumPy program to create a 3x3 identity matrix

In [15]:
np.identity(3,dtype = float)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Write a NumPy program to generate a random number between 0 and 1

In [17]:
np.random.rand(5,1)

array([[0.29244847],
       [0.20725881],
       [0.13811397],
       [0.32708343],
       [0.4241739 ]])

# Write a NumPy program to generate an array of 15 random numbers from a standard normal 
distribution

In [24]:
np.random.normal(1,20, 15)

array([-27.59701689,  19.04634525, -22.41390751, -10.26111591,
         3.12345826,  -6.70144515, -20.29176078, -14.87176103,
        16.2077043 ,   0.49014906,  -3.31536263, -21.9946392 ,
       -10.01320973, -12.28526955, -44.8120453 ])

# Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [27]:
np.random.randint(15.1,55,(1,10))

array([[46, 45, 34, 28, 15, 21, 44, 19, 20, 35]])

# Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10

In [30]:
np.random.randint(0,10.1,(1,5))

array([[1, 2, 3, 5, 4]])

# Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal 
to 1, and inside 0.

In [31]:
x=np.ones((10,10))
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [33]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

# Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main 
diagonal.

In [36]:
x=np.zeros((4,4))
x[0::2,1::2]=1
x[1::2,0::2]=1
x

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

# Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it.

# Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values. 
Select

In [37]:
np.random.rand(40)

array([0.59019448, 0.09479348, 0.82542979, 0.00476513, 0.07718145,
       0.53276137, 0.7956361 , 0.37220431, 0.44025628, 0.89717349,
       0.3151182 , 0.86806407, 0.21402906, 0.62058714, 0.36098183,
       0.87305259, 0.98316833, 0.31668955, 0.16174129, 0.3575622 ,
       0.16132734, 0.73559504, 0.11473842, 0.57387885, 0.43143475,
       0.80727937, 0.47515799, 0.12781713, 0.94707593, 0.84894336,
       0.19771613, 0.00861699, 0.38668314, 0.78975349, 0.18743916,
       0.88401457, 0.93185233, 0.99783719, 0.51150085, 0.84777605])

# Write a NumPy program to extract all numbers from a given array which are less and greater than a 
specified number.

In [39]:
x=np.array([1,2,5,7,11,25,12,41,21,10,9,6])
n=10
o=17
print(x[x<n])
print(x[x>o])

[1 2 5 7 9 6]
[25 41 21]
